name: flutter_lyra
description: This package allows you to use the methods from the lyra android and ios native sdks in Flutter
version: 0.2.1
homepage: https://github.com/bamlab/Flutter-Lyra
repository: https://github.com/bamlab/Flutter-Lyra

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_lyra_android
      ios:
        default_package: flutter_lyra_ios

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_lyra_android: ^0.2.1
  flutter_lyra_ios: ^0.2.1
  flutter_lyra_platform_interface: ^0.2.1
dev_dependencies:
  analyzer: ^4.7.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.0.0
