name: Test Flutter Payzen iOS

on:
  push:
    paths:
      - "flutter_payzen_ios/**"
      - ".github/workflows/flutter_payzen_ios.yaml"
    branches:
      - main
  pull_request:
    paths:
      - "flutter_payzen_ios/**"
      - ".github/workflows/flutter_payzen_ios.yaml"
    branches:
      - main

jobs:
  test:
    strategy:
      matrix: {dir: ["flutter_payzen_ios"]}
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ${{ matrix.dir }}

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2.5.0
        with:
          flutter-version: 3.3.0
          channel: "stable"
          cache: true
          cache-key: ${{ runner.os }}-flutter-3.3.0
          cache-path: ${{ runner.tool_cache }}/flutter-3.3.0

      - name: Install Dependencies
        run: flutter packages get

      - name: Format
        run: flutter format --set-exit-if-changed lib test

      - name: Analyze
        run: flutter analyze lib test

      - name: Run tests
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random

      - name: Install Remove From Coverage
        run: dart pub global activate remove_from_coverage

      - name: Remove from coverage generated files
        run: remove_from_coverage -f coverage/lcov.info -r '\.gql\.dart$|\.g\.dart$|\.freezed\.dart$'

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.2.0
        with:
          path: "./${{ matrix.dir }}/coverage/lcov.info"
          min_coverage: 100
